### ISSUE TITLE
Ch. 17 lib/i2a.py using tensor with wrong type as an index

### ISSUE THREAD

**Issue by stevenapsel** [PacktPublishing/Deep-Reinforcement-Learning-Hands-On#11]
While running 03_i2a.py, I get a runtime error on line 61 of lib/i2a.py:
act_planes_v[range(batch_size), actions] = 1.0

_actions_ is being used as an index, and the tensor types needs to be int or byte.
To fix this, I made the following change on line 166:
actions_t = torch.tensor(actions,**dtype=torch.int64**).to(batch.device) 

I am now able to run without issues.

**Comment by Shmuma** [comment]
Fixed by PR12, thanks for reporting!
