### ISSUE TITLE
Ch. 15 Trpo algorithm's implementation: get_kl  method

### ISSUE THREAD

**Issue by lanseyege** [PacktPublishing/Deep-Reinforcement-Learning-Hands-On#17]
Hi:
In Chp 15, trpo's KL distance is implemented by following code:
  kl = logstd_v - logstd0_v + (std0_v ** 2 + ((mu0_v - mu_v) ** 2) / (2.0 * std_v ** 2)) - 0.5
While,  based on this link
https://stats.stackexchange.com/questions/7440/kl-divergence-between-two-univariate-gaussians
should the kl distance of two Normal distributions be this: 
  kl = logstd_v - logstd0_v + (std0_v ** 2 + (mu0_v - mu_v) ** 2) / (2.0 * std_v ** 2) - 0.5

**Comment by Shmuma** [comment]
Yep, looks like a bug! Thanks!

**Comment by Shmuma** [comment]
Fixed, thanks!
