### ISSUE TITLE
Chapter 6: dqn_pong Confusing statement

### ISSUE THREAD

**Issue by gowtham1997** [PacktPublishing/Deep-Reinforcement-Learning-Hands-On#18]
This is regarding line 77(`new_state = new_state`) in dqn_pong.      

        new_state, reward, is_done, _ = self.env.step(action)

        self.total_reward += reward

        new_state = new_state

was this supposed to be self.state = new_state (which is done in line 81)?

**Comment by icompute386** [comment]
was this the solution?

**Comment by Shmuma** [comment]
> was this supposed to be self.state = new_state (which is done in line 81)?

No, this line need to be removed (already done in master branch). This place is too early to do assignment, as we still need old state
