### ISSUE TITLE
a3c not working on windows?

### ISSUE THREAD

**Issue by Fable67** [PacktPublishing/Deep-Reinforcement-Learning-Hands-On#2]
I can't run the 01_a3c_data.py and 02_a3c_grad.py file in chapter11 on windows. 
I get this error: 
`
    THCudaCheck FAIL file=c:\users\administrator\downloads\new-builder\win- 
    wheel\pytorch\torch\csrc\generic\StorageSharing.cpp line=253 error=63 : OS call failed or operation 
    not supported on this OS<br>
`

What can I do to continue the tutorial?

**Comment by izabael** [comment]
Probably not the answer you want to hear but I'd suggest installing everything on Ubuntu (or I personally prefer Linux Mint which is based on Ubuntu).  You'll have less headaches in general with all your future deep learning endeavors, and when you do have problems you'll find a lot more help online.  That has been my experience as someone new to this world.

**Comment by Shmuma** [comment]
Hi! 

Sorry for late reply, I've missed this thread somehow.

It was stated in chapter2, section "Hardware and software requirements" that samples haven't been tested on windows. In fact, linux was a primary os used for writing all examples of the book. Some might work on windows, but it is not guaranteed, sorry.

Specifically for your problem, it looks like pytorch have issues sharing the tensor on windows. This is described here (at the end), but it doesn't look like a solution: 
https://shiftlab.github.io/pytorch_docs/notes/windows.htm

I can suggest you to install linux in the cloud or in a virtual machine.
