### ISSUE TITLE
A3C Bug?

### ISSUE THREAD

**Issue by gowtham1997** [PacktPublishing/Deep-Reinforcement-Learning-Hands-On#33]
Hello, 

This is regarding line 104-107 in 01_a3c_data.py https://github.com/PacktPublishing/Deep-Reinforcement-Learning-Hands-On/blob/71617994fbefcf7c432cb229f007942d3b0d450c/Chapter11/01_a3c_data.py#L104-L107

On line 104, we are calculating loss between _value_v_ and _vals_ref_v_ after squeezing _value_v_ as its shape is (batch_size, 1) while _vals_ref_v_ has the shape (batch_size). This is clear to me. 

But on line 107, we aren't squeezing _value_v_ before subtracting from _values_ref_v_ and the resulting _adv_v_ vector has the shape (batch_size, batch_size) and this also influences the shape of log_prob_actions_v at line 108.

And this _adv_v_ calculation is used in a2c.py(chapter 10) as well.

Is this a bug? I haven't compared the code with and without squeezing _value_v_ at line 107 but I am confused after inspecting the shapes.

**Comment by liuyuezhangadam** [comment]
Hi, I just read the code days ago and I don't think  it's a bug. 

It's just broadcasting. Tough it got more copies of the values, it was averaged by the mean() function in the line after.

**Comment by gowtham1997** [comment]
Yes, makes sense.

Thanks for clarifying.
