### ISSUE TITLE
Possible bug in Chapter08/lib/data.py

### ISSUE THREAD

**Issue by educob** [PacktPublishing/Deep-Reinforcement-Learning-Hands-On#42]
Hi.

in line 33 it asks if prev_vals is not None but then it's not used.

```
if fix_open_price and prev_vals is not None:
                ppo, pph, ppl, ppc, ppv = vals
```

I think line 34 should be:
`ppo, pph, ppl, ppc, ppv = prev_vals`

Thanks.

**Comment by Transigent** [comment]
I just came here to suggest exactly the same fix.

**Comment by Shmuma** [comment]
Thanks! Fixed in master
