### ISSUE TITLE
List comprehension

### ISSUE THREAD

**Issue by StrangeTcy** [PacktPublishing/Deep-Reinforcement-Learning-Hands-On#56]
Is there any specific reason you're not using list comprehensions? It seems much more "pythonic" than dealing with lists, maps and lambdas.
For example, in [crossentropy_cartpole](https://github.com/PacktPublishing/Deep-Reinforcement-Learning-Hands-On/blob/master/Chapter04/01_cartpole.py) you're getting rewards from a batch like this:
```python
def filter_batch(batch, percentile):
    rewards = list(map(lambda s: s.reward, batch))
```

while the same could be written as
```python
def filter_batch(batch, percentile):
    rewards = [s.reward for s in batch]
```
,which (to me, anyway) looks cleaner and easier to understand.

**Comment by Shmuma** [comment]
Hi!

You're right, your version is better and has the same semantics. Don't
remember why I used map and list :)

пт, 23 авг. 2019 г., 17:07 Maxim Smirnov <notifications@github.com>:

**Comment by StrangeTcy** [comment]
Ok then :-)
