### ISSUE TITLE
Missing Chapter03/04_atari_gan_ignite.py file 

### ISSUE THREAD

**Issue by neonguru** [PacktPublishing/Deep-Reinforcement-Learning-Hands-On#69]
Missing Chapter03/04_atari_gan_ignite.py
This file is referred to in Chapter 3 of the book in the "ignite concepts" section, but it cannot be found in the repository.

**Comment by Shmuma** [comment]
That's a repository for the first edition of the book. Ignite was introduced in the second edition: https://github.com/PacktPublishing/Deep-Reinforcement-Learning-Hands-On-Second-Edition

**Comment by neonguru** [comment]
Thanks
