### ISSUE TITLE
License

### ISSUE THREAD

**Issue by benjaminbluhm** [PacktPublishing/Deep-Reinforcement-Learning-Hands-On#70]
Hi,

I would like to use part of your repo for a project. Can you tell us what the license is?

Legally, without a license, no one can use your code:

https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license

Would be great if you could add a license.

**Comment by Shmuma** [comment]
Hi! Thanks for reporting. Added MIT license with https://github.com/PacktPublishing/Deep-Reinforcement-Learning-Hands-On/commit/568a00479bce5089bae5a697b84d2db76f24b8d1
