### ISSUE TITLE
Chapter 3 04_stari_gan_ignite.py missing

### ISSUE THREAD

**Issue by dkinneyBU** [PacktPublishing/Deep-Reinforcement-Learning-Hands-On#85]
The book states the following, on page 79: The full example code is available in Chapter03/04_atari_gan_ignite.py. This script appears to be missing from the repo.

thanks
Dave

**Comment by Shmuma** [comment]
Hi! That's a first edition repo. Second edition's examples is on the
separate repo:
https://github.com/PacktPublishing/Deep-Reinforcement-Learning-Hands-On-Second-Edition

вс, 11 окт. 2020 г., 18:21 Dave Kinney <notifications@github.com>:

**Comment by dkinneyBU** [comment]
Perfect--thanks Shmuma!
